#!/bin/bash
echo -ne "--------------------- Date Generator ---------------------\n\nEnter dates in the following format\n\nFirst date: YYYY-MM-DD  -  Last date: YYYY-MM-DD\n\n 			ex. 1991-5-6 <-> 2016-12-3\n\n"

FLAG=1
while [[ "$FLAG" != 0 ]]; do
	read -rp "Enter first date: " FIRST_DATE
	read -rp "Enter last date: " LAST_DATE
	if [[ -z "$FIRST_DATE" ]] && [[ -z "$LAST_DATE" ]]; then
		FIRST_DATE="1940-1-1"
		LAST_DATE="2017-12-31"
		echo -ne "\nUsing default dates 1940-1-1 <-> 2017-12-31\n\n"
		DATE_DIFF=$(( ( $(date -ud $LAST_DATE +'%s') - $(date -ud $FIRST_DATE +'%s') )/60/60/24 ))
		FLAG=0
		break
	else
		date +%d/%m/%Y -ud "$FIRST_DATE" >> /dev/null
		FDATE_IS_VALID="$?"
		date +%d/%m/%Y -ud "$LAST_DATE" >> /dev/null
		LDATE_IS_VALID="$?"
		if [[ "$FDATE_IS_VALID" != 0 ]] || [[ "$LDATE_IS_VALID" != 0 ]]; then
			echo "Invalid dates inserted..."
			FLAG=1
		else
			DATE_DIFF=$(( ( $(date -ud $LAST_DATE +'%s') - $(date -ud $FIRST_DATE +'%s') )/60/60/24 ))
			if [[ "$DATE_DIFF" -gt 0 ]]; then
				FLAG=0
				break
			else
				echo "Last date is more recent than first..."
				FLAG=1
			fi
		fi
	fi
done

##Save As
DATE_LIST=$(seq 1 "$DATE_DIFF")
echo "Please wait... Generating dates."
NAME_F=$(awk -F '-' '{print $1}' <<< $FIRST_DATE)
NAME_L=$(awk -F '-' '{print $1}' <<< $LAST_DATE)

for i in $DATE_LIST
do
	date -d "$FIRST_DATE $i days" +%d%m%Y >> "$NAME_F-$NAME_L".lst
done
echo -ne "\nDates generated succesfully\nSaved as $NAME_F-$NAME_L.lst"